In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv('/home/mohan/Downloads/bq-results-20190615-143813-1d5hlvbhmu0a.csv')
df1 = df

In [3]:
df1['labelling_procedure'] = df['labelling_procedure'].apply(lambda x: x if x == 'direct' else 0)

In [4]:
df1 = df1[df1.labelling_procedure != 0]

In [5]:
df1['age_id'] = df1['age_id'].apply(lambda x: 100 if x>=100 else x)

/home/mohan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df1['age_id'] = df1['age_id'].apply(lambda x: df1.age_id.value_counts())

In [17]:
for i in range(len(df)):
    if df1['age_id'][i].value_counts<2:
        df['age_id'][i] = df['age_id'][i] + 1

AttributeError: 'numpy.int64' object has no attribute 'value_counts'

In [11]:
df1.age_id.value_counts()

1      763
45     751
26     616
44     614
46     587
43     580
42     483
24     467
32     437
40     390
47     371
29     369
27     338
25     333
39     313
28     306
41     301
2      258
30     209
35     203
31     183
3      176
4      172
8      161
38     161
58     150
33     150
23     144
65     139
16     139
      ...
59      47
73      44
13      43
78      41
66      34
57      33
82      28
69      27
64      27
11      23
76      23
71      22
19      22
88      22
74      19
86      18
79      17
89      17
81      15
100     14
83      14
77      11
92      11
84      11
96      10
95       4
87       3
99       3
93       2
91       1
Name: age_id, Length: 97, dtype: int64

In [21]:
df1[df1.age_id == 91]

Empty DataFrame
Columns: [gender_id, age_id, frame_id, labelling_procedure]
Index: []

In [20]:
df1.drop([22915],inplace=True)

/home/mohan/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
train, test = train_test_split(df1, test_size=0.2, random_state=42, 
                               stratify=df1[['age_id']])

In [25]:
test.to_csv()

,gender_id,age_id,frame_id,labelling_procedure
10056,male,32,32_DJ_Qualls_0008.jpg,direct
1289,female,3,3_1_3_20161219225754439.jpg.chip.jpg,direct
854,female,1,1_0_0_20161219192713491.jpg.chip.jpg,direct
13749,male,42,42_Russell_Crowe_0001.jpg,direct
10680,male,33,33_Hugh_Dancy_0009.jpg,direct
12163,male,38,38_Nikolaj_Coster-Waldau_0016.jpg,direct
5695,female,22,22_1_3_20170104234459677.jpg.chip.jpg,direct
22058,female,80,80_1_4_20170110184132973.jpg.chip.jpg,direct
13658,male,42,42_Steve_Carell_0012.jpg,direct
14385,male,43,43_Matt_Damon_0010.jpg,direct
21156,female,72,72_1_0_20170110180453423.jpg.chip.jpg,direct
15022,male,44,44_Joss_Whedon_0004.jpg,direct
9785,female,31,31_1_1_20170112231537686.jpg.chip.jpg,direct
18932,male,58,58_0_2_20170116193608936.jpg.chip.jpg,direct
20346,male,66,66_0_0_20170120225917395.jpg.chip.jpg,direct
16776,male,46,46_Jon_Favreau_0009.jpg,direct
4062,female,15,15_1_4_20170103233441003.jpg.chip.jpg,direct
8887,female,29,29_1_0_20170104023227077.jpg.chip.jpg,direct
329,female,1,1_1_0_20170109190939585.jpg.chip.jpg,direct
3591,female,12,12_1_2_20170103200922406.jpg.chip.jpg,direct
7204,male,26,26_Jay_Baruchel_0008.jpg,direct
623,female,1,1_1_0_20170109194142307.jpg.chip.jpg,direct
19215,male,60,60_0_0_20170113184242864.jpg.chip.jpg,direct
20853,male,70,70_0_0_20170117174648902.jpg.chip.jpg,direct
22177,male,82,82_0_0_20170111210140987.jpg.chip.jpg,direct
9228,male,30,30_Nick_Cannon_0006.jpg,direct
291,female,1,1_0_3_20161220223250813.jpg.chip.jpg,direct
21017,female,70,70_1_0_20170110141008498.jpg.chip.jpg,direct
8822,male,29,29_Jay_Baruchel_0003.jpg,direct
7092,male,26,26_0_3_20170105175423430.jpg.chip.jpg,direct
...,...,...,...,...
6582,female,24,24_1_3_20161220221541210.jpg.chip.jpg,direct
6818,female,25,25_1_3_20170117141253241.jpg.chip.jpg,direct
15866,male,45,45_Michael_K._Williams_0003.jpg,direct
11473,female,35,35_1_2_20170109010122762.jpg.chip.jpg,direct
17126,male,47,47_H._Jon_Benjamin_0002.jpg,direct
11280,male,35,35_0_0_20170117151812445.jpg.chip.jpg,direct
9106,male,30,30_0_2_20170116163100468.jpg.chip.jpg,direct
1863,female,4,4_1_3_20161220221751466.jpg.chip.jpg,direct
22190,male,82,82_0_2_20170112224626730.jpg.chip.jpg,direct
4106,female,15,15_1_0_20170109214058590.jpg.chip.jpg,direct
8462,female,28,28_1_2_20170116172552663.jpg.chip.jpg,direct
18975,male,58,58_0_1_20170113185358000.jpg.chip.jpg,direct
17150,male,47,47_Ben_Stiller_0009.jpg,direct
2352,female,6,6_1_0_20170104010034799.jpg.chip.jpg,direct
13084,female,40,40_1_0_20170120133632861.jpg.chip.jpg,direct
13548,female,41,41_Maya_Rudolph_0008.jpg,direct
5425,female,20,20_1_0_20170117193612788.jpg.chip.jpg,direct
7789,male,27,27_0_4_20170117202117229.jpg.chip.jpg,direct
7810,male,27,27_Miko_Hughes_0005.jpg,direct
7624,female,26,26_1_1_20170116231834520.jpg.chip.jpg,direct
13518,female,41,41_Catherine_Zeta-Jones_0016.jpg,direct
18250,female,53,53_1_0_20170110160643297.jpg.chip.jpg,direct
12969,male,40,40_Eric_Bana_0010.jpg,direct
10615,male,33,33_Corey_Haim_0002.jpg,direct
7752,male,27,27_James_McAvoy_0007.jpg,direct
8169,female,27,27_1_2_20170116165932169.jpg.chip.jpg,direct
13694,male,42,42_Gavin_Hood_0017.jpg,direct
10889,male,34,34_0_1_20170113135659457.jpg.chip.jpg,direct
16513,male,46,46_Liam_Cunningham_0007.jpg,direct
6415,female,24,24_1_0_20170117150817978.jpg.chip.jpg,direct